//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDERDETAILs = new HashSet<ORDERDETAIL>();
        }
    
        public int OrderId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string status { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PAYMENT PAYMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAIL> ORDERDETAILs { get; set; }
    }
}
