//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WISHLIST
    {
        public int WishlistId { get; set; }
        public int ProductId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
